// Central product catalog for 3DTopia — edit prices, names, and image paths here.
// `image` should point to a file under /public/images/products/. If the file
// doesn't exist yet (or fails to load), the product card automatically falls
// back to a hand-drawn placeholder icon so nothing ever looks "broken".

export const formatIDR = (amount) => `Rp${Number(amount).toLocaleString('id-ID')}`

export const keychainFilters = ['All', 'Fandom', 'Food & Drink', 'Animals', 'Custom Initials']

export const keychainProducts = [
  {
    id: 'kc-sleepy-neko',
    name: 'Sleepy Neko',
    collection: 'Animals Collection',
    category: 'Animals',
    price: 35000,
    image: '/images/products/keychain-sleepy-neko.jpg',
    icon: 'Cat',
    bg: 'bg-secondary-container',
    iconColor: 'text-on-secondary-container',
  },
  {
    id: 'kc-corgi-butt',
    name: 'Corgi Butt',
    collection: 'Animals Collection',
    category: 'Animals',
    price: 38000,
    image: '/images/products/keychain-corgi-butt.jpg',
    icon: 'Corgi',
    bg: 'bg-tertiary-fixed',
    iconColor: 'text-on-tertiary-fixed-variant',
  },
  {
    id: 'kc-baby-owl',
    name: 'Baby Owl',
    collection: 'Animals Collection',
    category: 'Animals',
    price: 36000,
    image: '/images/products/keychain-baby-owl.jpg',
    icon: 'Owl',
    bg: 'bg-secondary-fixed',
    iconColor: 'text-on-secondary-fixed-variant',
  },
  {
    id: 'kc-sunny-egg-pan',
    name: 'Sunny Egg Pan',
    collection: 'Foodie Miniatures',
    category: 'Food & Drink',
    price: 40000,
    image: '/images/products/keychain-sunny-egg-pan.jpg',
    icon: 'EggPan',
    bg: 'bg-soft-yellow',
    iconColor: 'text-on-tertiary-container',
  },
  {
    id: 'kc-mini-avocado',
    name: 'Mini Avocado',
    collection: 'Foodie Miniatures',
    category: 'Food & Drink',
    price: 30000,
    image: '/images/products/keychain-mini-avocado.jpg',
    icon: 'Avocado',
    bg: 'bg-secondary-container',
    iconColor: 'text-on-secondary-container',
  },
  {
    id: 'kc-bubble-tea',
    name: 'Bubble Tea Cup',
    collection: 'Foodie Miniatures',
    category: 'Food & Drink',
    price: 32000,
    image: '/images/products/keychain-bubble-tea.jpg',
    icon: 'BubbleTea',
    bg: 'bg-tertiary-container',
    iconColor: 'text-on-tertiary-fixed-variant',
  },
  {
    id: 'kc-custom-letter-block',
    name: 'Custom Letter Block',
    collection: 'Personalized',
    category: 'Custom Initials',
    price: 25000,
    priceFrom: true,
    customizable: true,
    image: '/images/products/keychain-custom-letter-block.jpg',
    icon: 'Letters',
    bg: 'bg-lavender-accent',
    iconColor: 'text-on-tertiary-container',
  },
  {
    id: 'kc-custom-initial-charm',
    name: 'Custom Initial Charm',
    collection: 'Personalized',
    category: 'Custom Initials',
    price: 20000,
    priceFrom: true,
    customizable: true,
    image: '/images/products/keychain-custom-initial-charm.jpg',
    icon: 'Charm',
    bg: 'bg-primary-fixed',
    iconColor: 'text-on-primary-fixed-variant',
  },
]

export const bookmarkFilters = ['All Designs', 'Animals', 'Nature', 'Customizable']

export const bookmarkProducts = [
  {
    id: 'bm-sleepy-kitty-paw',
    name: 'Sleepy Kitty Paw',
    category: 'Animals',
    price: 35000,
    image: '/images/products/bookmark-sleepy-kitty-paw.jpg',
    icon: 'Paw',
    bg: 'bg-primary-fixed',
    iconColor: 'text-on-primary-fixed-variant',
    blurb: 'Soft pastel pink with white toe beans.',
  },
  {
    id: 'bm-geo-mountains',
    name: 'Geo Mountains',
    category: 'Nature',
    price: 38000,
    image: '/images/products/bookmark-geo-mountains.jpg',
    icon: 'Mountain',
    bg: 'bg-tertiary-fixed',
    iconColor: 'text-on-tertiary-fixed-variant',
    blurb: 'Minimalist peaks in dual-tone extrusion.',
  },
  {
    id: 'bm-potted-succulent',
    name: 'Potted Succulent',
    category: 'Nature',
    price: 42000,
    image: '/images/products/bookmark-potted-succulent.jpg',
    icon: 'Succulent',
    bg: 'bg-secondary-container',
    iconColor: 'text-on-secondary-container',
    blurb: 'A tiny garden for your current read.',
  },
  {
    id: 'bm-moon-phase',
    name: 'Moon Phase Arc',
    category: 'Nature',
    price: 40000,
    image: '/images/products/bookmark-moon-phase.jpg',
    icon: 'Moon',
    bg: 'bg-lavender-accent',
    iconColor: 'text-on-tertiary-container',
    blurb: 'A gentle crescent arc in matte lavender.',
  },
  {
    id: 'bm-owl-perch',
    name: 'Owl Perch',
    category: 'Animals',
    price: 36000,
    image: '/images/products/bookmark-owl-perch.jpg',
    icon: 'Owl',
    bg: 'bg-secondary-fixed',
    iconColor: 'text-on-secondary-fixed-variant',
    blurb: 'A wide-eyed little owl keeping watch on your page.',
  },
  {
    id: 'bm-butterfly-wing',
    name: 'Butterfly Wing',
    category: 'Animals',
    price: 34000,
    image: '/images/products/bookmark-butterfly-wing.jpg',
    icon: 'Butterfly',
    bg: 'bg-primary-container',
    iconColor: 'text-on-primary-container',
    blurb: 'Symmetric wings in a soft rose gradient.',
  },
  {
    id: 'bm-custom-script-name',
    name: 'Custom Script Name',
    category: 'Customizable',
    price: 48000,
    priceFrom: true,
    customizable: true,
    image: '/images/products/bookmark-custom-script-name.jpg',
    icon: 'Script',
    bg: 'bg-lavender-accent',
    iconColor: 'text-on-tertiary-container',
    blurb: 'Personalized with up to 10 characters.',
  },
  {
    id: 'bm-custom-initial-tab',
    name: 'Custom Initial Tab',
    category: 'Customizable',
    price: 22000,
    priceFrom: true,
    customizable: true,
    image: '/images/products/bookmark-custom-initial-tab.jpg',
    icon: 'Charm',
    bg: 'bg-soft-yellow',
    iconColor: 'text-on-tertiary-container',
    blurb: 'A small tab with your initial, in any color.',
  },
]
