/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#847376',
        'on-error-container': '#93000a',
        primary: '#884c5d',
        'inverse-surface': '#342f2e',
        tertiary: '#6a5c4d',
        'on-surface-variant': '#514346',
        'surface-dim': '#e1d8d5',
        'on-primary-fixed': '#370b1a',
        'on-primary-fixed-variant': '#6c3645',
        'on-secondary-container': '#58674f',
        'surface-bright': '#fff8f6',
        'deep-rose': '#CC7A8D',
        'inverse-on-surface': '#f8efec',
        'primary-container': '#f0a6b8',
        'on-secondary-fixed': '#121f0c',
        'on-primary': '#ffffff',
        'surface-container-low': '#fbf2ef',
        'on-tertiary-container': '#55483a',
        'inverse-primary': '#fdb2c4',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'lavender-accent': '#E2D9F3',
        'surface-container': '#f5ece9',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#fdb2c4',
        background: '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#bbccaf',
        'on-primary-container': '#713949',
        secondary: '#54634b',
        'on-tertiary-fixed': '#231a0e',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#3c4b35',
        'on-background': '#1e1b19',
        'secondary-fixed': '#d7e8ca',
        'outline-variant': '#d6c2c5',
        'on-error': '#ffffff',
        'surface-container-high': '#efe6e3',
        'surface-tint': '#884c5d',
        'soft-yellow': '#FFF5C2',
        'tertiary-fixed': '#f3dfcd',
        'cream-bg': '#F9F3EA',
        'secondary-container': '#d4e5c7',
        surface: '#fff8f6',
        'primary-fixed': '#ffd9e0',
        'surface-container-highest': '#e9e1de',
        'tertiary-container': '#c9b7a5',
        'tertiary-fixed-dim': '#d6c3b1',
        'on-tertiary-fixed-variant': '#514537',
        'surface-variant': '#e9e1de',
        'on-surface': '#1e1b19',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'section-gap-lg': '120px',
        'section-gap-md': '80px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        base: '8px',
      },
      fontFamily: {
        'label-sm': ['Be Vietnam Pro'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-lg': ['Be Vietnam Pro'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'label-md': ['Be Vietnam Pro'],
        'body-md': ['Be Vietnam Pro'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
